# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target "HHSdk" do
    project 'HHSdk.xcodeproj'
	pod 'Bolts'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod ‘FBSDKCoreKit’
	pod 'SVProgressHUD'
    pod 'Google/SignIn'
pod 'AFNetworking'
end

