# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/trungnghia/SdkSpec1.git’

target 'DeMoHHSdk' do
    #pod 'HHSdk', :path => ‘../../Pod_dir’
    pod 'HHSdk'



end
